# Generated by Django 6.0.3 on 2026-08-28 21:40

import erp_core.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundemail',
            name='context_version_id',
            field=models.CharField(blank=True, help_text='ID of the specific version linked to this email (e.g. ProposalVersion.id)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='senderidentity',
            name='smtp_password',
            field=erp_core.encryption.EncryptedCharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='senderidentity',
            name='verification_status',
            field=models.CharField(choices=[('USABLE', 'Usable (System Default)'), ('UNVERIFIED', 'Unverified'), ('VERIFIED', 'SMTP Verified'), ('DISABLED', 'Disabled')], default='UNVERIFIED', help_text='USABLE=system default, VERIFIED=tenant SMTP validated, UNVERIFIED=credentials not yet validated, DISABLED=cannot send.', max_length=20),
        ),
    ]
