# Generated by Django 6.0.3 on 2026-08-30 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_outboundemail_context_version_id_and_more'),
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(default='My Signature', max_length=100)),
                ('signature_type', models.CharField(choices=[('TEXT', 'Text / Rich Text'), ('IMAGE', 'Signature Image')], default='TEXT', max_length=20)),
                ('text_content', models.TextField(blank=True, default='', help_text='HTML or rich text signature')),
                ('image', models.ImageField(blank=True, null=True, upload_to='communications/signatures/%Y/%m/')),
                ('is_default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
