# Generated by Django 6.0.3 on 2026-08-28 22:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('crm', '0004_opportunity_proposal_opportunityaward_proposalline'),
        ('security_crm', '0002_alter_securityproposal_proposal_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityProposalMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('meeting_type', models.CharField(choices=[('FACE_TO_FACE', 'Face-to-Face'), ('ONLINE', 'Online / Video Call'), ('PHONE', 'Phone Call'), ('OTHER', 'Other')], default='FACE_TO_FACE', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('meeting_link', models.URLField(blank=True, default='', max_length=500)),
                ('agenda', models.TextField(blank=True, default='')),
                ('discussion_notes', models.TextField(blank=True, default='')),
                ('client_requirements', models.TextField(blank=True, default='')),
                ('commercial_concerns', models.TextField(blank=True, default='')),
                ('operational_concerns', models.TextField(blank=True, default='')),
                ('agreed_points', models.TextField(blank=True, default='')),
                ('pending_items', models.TextField(blank=True, default='')),
                ('outcome', models.CharField(blank=True, choices=[('PROCEED_TO_SITE_ASSESSMENT', 'Proceed to Site Assessment'), ('NEED_ANOTHER_MEETING', 'Need Another Meeting'), ('REVISE_PROPOSAL', 'Client Requested Revised Commercial Proposal'), ('ON_HOLD', 'On Hold'), ('REJECTED', 'Rejected'), ('NO_ACTION', 'No Immediate Action'), ('OTHER', 'Other')], default='', max_length=50)),
                ('outcome_notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_security_meetings', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='security_crm.securityproposal')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_security_followups', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_security_followups', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='security_crm.securityproposal')),
                ('related_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='security_crm.securityproposalmeeting')),
            ],
            options={
                'ordering': ['status', 'due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('participant_type', models.CharField(choices=[('INTERNAL_USER', 'Internal Staff'), ('CUSTOMER_CONTACT', 'Customer Contact'), ('EXTERNAL', 'External Attendee')], default='INTERNAL_USER', max_length=50)),
                ('external_name', models.CharField(blank=True, default='', max_length=255)),
                ('external_email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('attended', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('crm_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_meeting_participations', to='crm.crmcontact')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_meeting_participations', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='security_crm.securityproposalmeeting')),
            ],
            options={
                'ordering': ['participant_type', 'created_at'],
            },
        ),
    ]
