# Generated by Django 6.0.3 on 2026-08-28 23:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('security_crm', '0003_securityproposalmeeting_proposalfollowup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityassessment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='access_control',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='client_concerns',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='emergency_exits',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='entry_exit_points',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='existing_cctv',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='existing_guards',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='existing_security_setup',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='fire_safety_concerns',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='known_risks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='lighting_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='operating_hours',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='perimeter_security',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='sensitive_areas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='site_overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityassessment',
            name='visitor_management',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='securityassessment',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityassessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='securityassessment',
            unique_together={('proposal', 'client_location')},
        ),
        migrations.CreateModel(
            name='AssessmentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('SITE_PHOTO', 'Site Photo'), ('LAYOUT_DOCUMENT', 'Layout Document'), ('CLIENT_DOCUMENT', 'Client Document'), ('EXISTING_SETUP', 'Existing Security Setup'), ('OTHER', 'Other')], default='SITE_PHOTO', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='security_crm/assessments/%Y/%m/')),
                ('file_url', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='security_crm.securityassessment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentEquipmentRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('equipment_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('location_area', models.CharField(blank=True, default='', max_length=255)),
                ('purpose', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_recommendations', to='security_crm.securityassessment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentRiskFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='GENERAL', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('location_area', models.CharField(blank=True, default='', max_length=255)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='OPEN', max_length=50)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_findings', to='security_crm.securityassessment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentStaffingRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('shift_coverage_notes', models.CharField(blank=True, default='', max_length=255)),
                ('post_area', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.TextField(blank=True, default='')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_recommendations', to='security_crm.securityassessment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assessment_staffing_recommendations', to='security_crm.clientlocation')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assessment_staffing_recommendations', to='security_crm.securityservicetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
