# Generated by Django 6.0.3 on 2026-08-29 04:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('inventory', '0015_alter_itemserial_status_and_more'),
        ('security_crm', '0004_alter_securityassessment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractequipmentrequirement',
            name='charge_type',
            field=models.CharField(choices=[('ONE_TIME', 'One-Time'), ('MONTHLY', 'Monthly / Recurring')], default='ONE_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='contractequipmentrequirement',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_equipment_requirements', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='contractequipmentrequirement',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contractequipmentrequirement',
            name='source_recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_equipment_lines', to='security_crm.assessmentequipmentrecommendation'),
        ),
        migrations.AddField(
            model_name='contractequipmentrequirement',
            name='unit_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='proposalserviceline',
            name='source_recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_service_lines', to='security_crm.assessmentstaffingrecommendation'),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('BI_WEEKLY', 'Bi-Weekly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=50),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='commercial_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='contract_duration_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='discount_type',
            field=models.CharField(choices=[('NONE', 'None'), ('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='expected_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='payment_terms',
            field=models.CharField(choices=[('DUE_ON_RECEIPT', 'Due on Receipt'), ('NET_15', 'Net 15 Days'), ('NET_30', 'Net 30 Days'), ('NET_60', 'Net 60 Days'), ('ADVANCE', 'Advance Payment'), ('CUSTOM', 'Custom Terms')], default='NET_30', max_length=100),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='proposal_validity_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_security_proposal_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contractequipmentrequirement',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposalserviceline',
            name='billing_unit',
            field=models.CharField(default='MONTHLY', max_length=50),
        ),
        migrations.CreateModel(
            name='ProposalAdditionalCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('charge_name', models.CharField(max_length=150)),
                ('charge_type', models.CharField(choices=[('ONE_TIME', 'One-Time'), ('MONTHLY', 'Monthly / Recurring')], default='ONE_TIME', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('proposal_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='security_crm.proposalversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
