# Generated by Django 6.0.3 on 2026-08-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_crm', '0005_contractequipmentrequirement_charge_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('MEETING', 'Meeting'), ('SITE_ASSESSMENT', 'Site Assessment'), ('FINAL_PROPOSAL', 'Final Proposal'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('APPROVED', 'Approved'), ('SIGNING', 'Signing'), ('SIGNED', 'Signed'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50),
        ),
    ]
