# Generated by Django 6.0.3 on 2026-08-29 05:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('crm', '0004_opportunity_proposal_opportunityaward_proposalline'),
        ('security_crm', '0006_alter_proposalversion_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securityproposal',
            name='approval_method',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('WRITTEN', 'Written / Letter'), ('VERBAL', 'Verbal / Call'), ('PORTAL', 'Client Portal'), ('OTHER', 'Other')], default='EMAIL', max_length=50),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='approval_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='approved_by_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_security_proposals', to='crm.crmcontact'),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='approved_by_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='approved_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_proposals', to='security_crm.proposalversion'),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='billing_cycle',
            field=models.CharField(blank=True, default='MONTHLY', max_length=50),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='contract_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='expected_mobilization_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='on_hold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='on_hold_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='on_hold_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='payment_terms',
            field=models.CharField(blank=True, default='NET_30', max_length=100),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='rejection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='rejection_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='signed_by_client',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='signed_by_company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='signing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='signing_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ProposalSignedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('SIGNED_CONTRACT', 'Signed Contract'), ('SIGNED_PROPOSAL', 'Signed Proposal'), ('PURCHASE_ORDER', 'Purchase Order / PO'), ('AWARD_LETTER', 'Award Letter'), ('OTHER_SUPPORTING', 'Other Supporting Document')], default='SIGNED_CONTRACT', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='security_crm/signed_documents/%Y/%m/')),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_documents', to='security_crm.securityproposal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_security_signed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
