# Generated by Django 6.0.3 on 2026-08-29 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_crm', '0007_securityproposal_approval_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securityproposal',
            name='handoff_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='handoff_prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='handoff_prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_security_handoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='is_handoff_ready',
            field=models.BooleanField(default=False),
        ),
    ]
