# Generated by Django 6.0.3 on 2026-09-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_crm', '0008_securityproposal_handoff_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalserviceline',
            name='guard_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly base salary paid to guard deployed at this client location (PKR)', max_digits=15),
        ),
        migrations.AddField(
            model_name='proposalserviceline',
            name='shift_hours',
            field=models.CharField(blank=True, default='12_HOURS', help_text='Shift duration / coverage (e.g. 12_HOURS, 24_HOURS, 8_HOURS)', max_length=50),
        ),
        migrations.AddField(
            model_name='proposalserviceline',
            name='weapon_type',
            field=models.CharField(blank=True, default='UNARMED', help_text='Weapon or guard specialization category', max_length=50),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='overhead_per_guard',
            field=models.DecimalField(decimal_places=2, default=6000, help_text='Standard operational expense allocation per guard (default PKR 6,000)', max_digits=12),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='sales_tax_basis',
            field=models.CharField(choices=[('SERVICE_CHARGES', 'Service Charges'), ('TOTAL_SALE', 'Total Sale')], default='SERVICE_CHARGES', help_text='Sales tax calculation basis (service charges vs total sale)', max_length=30),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='service_charges_per_guard',
            field=models.DecimalField(decimal_places=2, default=3000, help_text='Monthly service charges per guard (default PKR 3,000)', max_digits=12),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='total_eobi',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total monthly EOBI contribution for institutional contracts', max_digits=15),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='total_sessi',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total monthly SESSI contribution for institutional contracts', max_digits=15),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='withholding_tax_basis',
            field=models.CharField(choices=[('SERVICE_CHARGES', 'Service Charges'), ('INVOICE_AMOUNT', 'Invoice Amount')], default='SERVICE_CHARGES', help_text='Withholding tax calculation basis', max_length=30),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='withholding_tax_rate',
            field=models.DecimalField(decimal_places=2, default=7, help_text='Income / Withholding Tax deduction rate % (default 7%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='proposalserviceline',
            name='client_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly client billing rate per head (PKR)', max_digits=15),
        ),
    ]
