# Generated by Django 6.0.3 on 2026-10-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_crm', '0009_proposalserviceline_guard_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalversion',
            name='sales_tax_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional manual rupee override for Sales Tax amount (PKR). If set, overrides formula.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='withholding_tax_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional manual rupee override for WHT amount (PKR). If set, overrides formula.', max_digits=15, null=True),
        ),
    ]
