# Generated by Django 6.0.3 on 2026-10-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_crmentity_code'),
        ('security_crm', '0010_proposalversion_sales_tax_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentstaffingrecommendation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_staffing_recommendations', to='security_crm.clientlocation'),
        ),
        migrations.AlterField(
            model_name='contractequipmentrequirement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_requirements', to='security_crm.clientlocation'),
        ),
        migrations.AlterField(
            model_name='proposalserviceline',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_lines', to='security_crm.clientlocation'),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='sales_tax_basis',
            field=models.CharField(choices=[('SERVICE_CHARGES', 'Service Charges'), ('TOTAL_SALE', 'Total Sale'), ('MANUAL', 'Manual Entry')], default='SERVICE_CHARGES', help_text='Sales tax calculation basis (service charges vs total sale vs manual entry)', max_length=30),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='withholding_tax_basis',
            field=models.CharField(choices=[('SERVICE_CHARGES', 'Service Charges'), ('INVOICE_AMOUNT', 'Invoice Amount'), ('MANUAL', 'Manual Entry')], default='SERVICE_CHARGES', help_text='Withholding tax calculation basis', max_length=30),
        ),
        migrations.AlterField(
            model_name='securityassessment',
            name='client_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='security_crm.clientlocation'),
        ),
        migrations.AlterField(
            model_name='securityproposal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_proposals', to='crm.crmentity'),
        ),
    ]
