# Generated by Django 6.0.3 on 2026-08-11 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial_platform_core'),
        ('crm', '0001_initial'),
        ('finance', '0007_salesaccountingconfiguration'),
        ('hrm', '0009_payrollrun_journal_entry_and_more'),
        ('operations', '0002_deployment_dutyassignment_extraduty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('crm_entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='service_invoices', to='crm.crmentity')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_invoices', to='finance.journalentry')),
                ('service_contract', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='service_invoices', to='operations.servicecontract')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source_duty_assignment_ids', models.JSONField(default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_lines', to='hrm.designation')),
                ('operational_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_lines', to='operations.operationalsite')),
                ('service_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.serviceinvoice')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingAccountingConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('accounts_receivable_account', models.ForeignKey(help_text='Accounts Receivable (Asset) account', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.currency')),
                ('service_revenue_account', models.ForeignKey(help_text='Service Revenue (Income) account', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company',), name='unique_active_billing_accounting_config')],
            },
        ),
        migrations.CreateModel(
            name='ExtraDutyPayrollBridge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('extra_duty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payroll_bridges', to='operations.extraduty')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='extra_duty_bridges', to='hrm.payrollrun')),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_duty_bridges', to='hrm.payslip')),
            ],
            options={
                'ordering': ['-processed_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'extra_duty', 'payroll_run'), name='unique_active_extra_duty_payroll_bridge')],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('invoice_number', ''), _negated=True)), fields=('company', 'invoice_number'), name='unique_active_service_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='serviceinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'service_contract', 'period_start', 'period_end'), name='unique_active_service_invoice_period'),
        ),
    ]
