# Generated by Django 6.0.3 on 2026-08-11 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('finance', '0007_salesaccountingconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccountingconfiguration',
            name='tax_payable_account',
            field=models.ForeignKey(blank=True, help_text='Tax Payable (Liability) account', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_invoices', to='finance.taxcode'),
        ),
    ]
