# Generated by Django 6.0.3 on 2026-08-11 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_phase8d'),
        ('companies', '0002_initial_platform_core'),
        ('finance', '0007_salesaccountingconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccountingconfiguration',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Cash/Bank (Asset) account for payments', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceInvoicePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='service_invoice_payments', to='finance.journalentry')),
                ('service_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.serviceinvoice')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('reference', ''), _negated=True)), fields=('company', 'service_invoice', 'reference'), name='unique_active_service_invoice_payment_reference')],
            },
        ),
    ]
