# Generated by Django 6.0.3 on 2026-08-11 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_phase8d_payment'),
        ('finance', '0007_salesaccountingconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinvoice',
            name='base_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_invoices', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=15),
        ),
    ]
