# Generated by Django 6.0.3 on 2026-08-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_phase8d_multicurrency'),
        ('operations', '0008_dutyassignment_temporary_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinvoice',
            name='service_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_invoices', to='operations.servicecontract'),
        ),
    ]
