# Generated by Django 6.0.3 on 2026-09-01 00:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_billingperiod_billingsheet_billingadjustment_and_more'),
        ('communications', '0003_useremailsignature'),
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('crm', '0005_alter_crmentity_code'),
        ('finance', '0010_securityfinanceconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinvoice',
            name='recovery_status',
            field=models.CharField(choices=[('NOT_DUE', 'Not Due'), ('DUE', 'Due'), ('UNDER_FOLLOWUP', 'Under Follow-up'), ('PROMISE_TO_PAY', 'Promise to Pay'), ('PARTIALLY_RECOVERED', 'Partially Recovered'), ('DISPUTED', 'Disputed'), ('ESCALATED', 'Escalated'), ('RECOVERED', 'Recovered')], default='NOT_DUE', max_length=30),
        ),
        migrations.CreateModel(
            name='ClientReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('receipt_number', models.CharField(blank=True, default='', max_length=100)),
                ('receipt_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=15)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash'), ('ONLINE', 'Online / Card'), ('PAY_ORDER', 'Pay Order'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=30)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('cheque_number', models.CharField(blank=True, default='', max_length=100)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('drawn_bank', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=30)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='client_receipts', to='finance.bankaccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='client_receipts', to='crm.crmentity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='client_receipts', to='finance.currency')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_client_receipts', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_client_receipts', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_client_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-receipt_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientReceiptAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receipt_allocations', to='billing.clientinvoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.clientreceipt')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('activity_type', models.CharField(choices=[('PHONE_CALL', 'Phone Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('PROMISE_TO_PAY', 'Promise to Pay'), ('DISPUTE', 'Dispute'), ('ESCALATION', 'Escalation'), ('OTHER', 'Other')], default='PHONE_CALL', max_length=30)),
                ('activity_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('promise_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('promise_date', models.DateField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('recovery_status_outcome', models.CharField(choices=[('NOT_DUE', 'Not Due'), ('DUE', 'Due'), ('UNDER_FOLLOWUP', 'Under Follow-up'), ('PROMISE_TO_PAY', 'Promise to Pay'), ('PARTIALLY_RECOVERED', 'Partially Recovered'), ('DISPUTED', 'Disputed'), ('ESCALATED', 'Escalated'), ('RECOVERED', 'Recovered')], default='UNDER_FOLLOWUP', max_length=30)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_recovery_activities', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_activities', to='crm.crmentity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recovery_activities', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_activities', to='billing.clientinvoice')),
                ('outbound_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_activities', to='communications.outboundemail')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='clientreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('receipt_number', ''), _negated=True)), fields=('company', 'receipt_number'), name='unique_active_client_receipt_number'),
        ),
        migrations.AddConstraint(
            model_name='clientreceiptallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('receipt', 'invoice'), name='unique_active_receipt_invoice_allocation'),
        ),
    ]
