# Generated by Django 6.0.3 on 2026-10-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_clientinvoice_recovery_status_clientreceipt_and_more'),
        ('operations', '0019_deployment_location_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingadjustment',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_adjustments', to='operations.operationalsite'),
        ),
        migrations.AlterField(
            model_name='billingsheetline',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_lines', to='operations.operationalsite'),
        ),
        migrations.AlterField(
            model_name='clientinvoiceline',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_invoice_lines', to='operations.operationalsite'),
        ),
        migrations.AlterField(
            model_name='serviceinvoiceline',
            name='operational_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='operations.operationalsite'),
        ),
    ]
