# Generated by Django 6.0.3 on 2026-08-04 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('finance', '0003_creditaccount_is_deleted_expense_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='crm_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crm.crmentity'),
        ),
    ]
