# Generated by Django 6.0.3 on 2026-08-05 19:34

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial_platform_core'),
        ('finance', '0004_creditaccount_crm_entity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JournalEntry',
            new_name='LegacyJournalEntry',
        ),
        migrations.AlterModelTable(
            name='legacyjournalentry',
            table='finance_journalentry',
        ),
    ]
