# Generated by Django 6.0.3 on 2026-08-06 03:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial_platform_core'),
        ('finance', '0006_accountgroup_costcenter_currency_chartofaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAccountingConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('accounts_receivable_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount')),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.currency')),
                ('rounding_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount')),
                ('sales_discount_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount')),
                ('sales_return_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount')),
                ('sales_revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount')),
                ('sales_tax_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company',), name='unique_active_sales_accounting_config')],
            },
        ),
    ]
