# Generated by Django 6.0.3 on 2026-08-31 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('finance', '0009_bankaccount_bankstatement_bankstatementline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityFinanceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='accountingperiod',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['account_title']},
        ),
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={'ordering': ['account_code']},
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='profitcenter',
            options={'ordering': ['code']},
        ),
        migrations.RemoveConstraint(
            model_name='bankaccount',
            name='unique_active_bank_account',
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='period_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('BANK', 'Bank'), ('CASH', 'Cash'), ('PETTY_CASH', 'Petty Cash'), ('WALLET', 'Digital Wallet')], default='BANK', max_length=20),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='allow_posting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='is_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='is_system_controlled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='normal_balance',
            field=models.CharField(blank=True, choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', max_length=10),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profitcenter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profitcenter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SOFT_CLOSED', 'Soft Closed'), ('CLOSED', 'Closed'), ('LOCKED', 'Locked')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.accountgroup'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('COST_OF_SERVICE', 'Cost of Service / COGS'), ('EXPENSE', 'Expense'), ('OTHER_INCOME', 'Other Income'), ('OTHER_EXPENSE', 'Other Expense')], max_length=50),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='finance.costcenter'),
        ),
        migrations.AlterField(
            model_name='profitcenter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='finance.profitcenter'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('account_number', ''), _negated=True)), fields=('company', 'account_number'), name='unique_active_bank_account'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_cost_center_code'),
        ),
        migrations.AddConstraint(
            model_name='profitcenter',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_profit_center_code'),
        ),
        migrations.AddField(
            model_name='securityfinanceconfiguration',
            name='accounts_payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='securityfinanceconfiguration',
            name='accounts_receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='securityfinanceconfiguration',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company'),
        ),
        migrations.AddField(
            model_name='securityfinanceconfiguration',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='securityfinanceconfiguration',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='securityfinanceconfiguration',
            name='extra_duty_revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='securityfinanceconfiguration',
            name='inventory_equipment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='securityfinanceconfiguration',
            name='overtime_cost_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='securityfinanceconfiguration',
            name='overtime_revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='securityfinanceconfiguration',
            name='payroll_payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='securityfinanceconfiguration',
            name='salary_cost_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='securityfinanceconfiguration',
            name='security_service_revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='securityfinanceconfiguration',
            name='tax_payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount'),
        ),
        migrations.AddConstraint(
            model_name='securityfinanceconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company',), name='unique_active_security_finance_config'),
        ),
    ]
