# Generated by Django 6.0.3 on 2026-09-01 04:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('crm', '0005_alter_crmentity_code'),
        ('finance', '0010_securityfinanceconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('MONEY_IN', 'Money In'), ('MONEY_OUT', 'Money Out'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('OPENING_BALANCE', 'Opening Balance')], default='MONEY_IN', max_length=30)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('money_in', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('money_out', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('running_balance', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('status', models.CharField(default='POSTED', max_length=20)),
                ('is_reversal', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cheque',
            options={'ordering': ['-issue_date', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='cheque',
            name='unique_active_cheque',
        ),
        migrations.RemoveConstraint(
            model_name='financialvoucher',
            name='unique_active_voucher_number',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_opening_balance_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='opening_balance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='opening_balance_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='opening_balance_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_bank_opening_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cheque',
            name='bounce_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cheque',
            name='bounced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounced_cheques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cheque',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_cheques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cheque',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cheques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cheque',
            name='drawer_bank',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='cheque',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cheque',
            name='payer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_financial_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Primary treasury bank/cash/wallet account', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vouchers', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='counterparty_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='destination_bank_account',
            field=models.ForeignKey(blank=True, help_text='Destination treasury account for contra transfers', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contra_destination_vouchers', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=15),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_financial_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='reversal_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='reversal_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_vouchers', to='finance.financialvoucher'),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_financial_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='source_document_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='source_document_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='financialvoucher',
            name='source_module',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='financialvoucherline',
            name='profit_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.profitcenter'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='cheque_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='payee_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='finance.financialvoucher'),
        ),
        migrations.AlterField(
            model_name='financialvoucher',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='financialvoucher',
            name='payee_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='financialvoucher',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Direct Chart of Account link', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vouchers', to='finance.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='financialvoucher',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('ONLINE_TRANSFER', 'Online Transfer'), ('DIRECT_DEPOSIT', 'Direct Deposit'), ('WALLET', 'Digital Wallet'), ('OTHER', 'Other')], default='CASH', max_length=30),
        ),
        migrations.AlterField(
            model_name='financialvoucher',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='financialvoucher',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='financialvoucher',
            name='voucher_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='financialvoucher',
            name='voucher_type',
            field=models.CharField(choices=[('RECEIPT_VOUCHER', 'Receipt Voucher'), ('PAYMENT_VOUCHER', 'Payment Voucher'), ('BANK_RECEIPT', 'Bank Receipt'), ('BANK_PAYMENT', 'Bank Payment'), ('CASH_RECEIPT', 'Cash Receipt'), ('CASH_PAYMENT', 'Cash Payment'), ('CONTRA_VOUCHER', 'Contra Voucher'), ('JOURNAL_VOUCHER', 'Journal Voucher'), ('PETTY_CASH_VOUCHER', 'Petty Cash Voucher'), ('PAYMENT', 'Payment Voucher (Legacy)'), ('RECEIPT', 'Receipt Voucher (Legacy)'), ('CONTRA', 'Contra Voucher (Legacy)'), ('JOURNAL', 'Journal Voucher (Legacy)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='financialvoucherline',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='financialvoucher',
            index=models.Index(fields=['company', 'status'], name='finance_fin_company_62f93e_idx'),
        ),
        migrations.AddIndex(
            model_name='financialvoucher',
            index=models.Index(fields=['company', 'source_document_type', 'source_document_id'], name='finance_fin_company_eed3dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='cheque',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status__in', ['ISSUED', 'DEPOSITED', 'CLEARED'])), fields=('company', 'bank_account', 'cheque_number'), name='unique_active_cheque'),
        ),
        migrations.AddConstraint(
            model_name='financialvoucher',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('voucher_number', ''), _negated=True)), fields=('company', 'voucher_number'), name='unique_active_voucher_number'),
        ),
        migrations.AddConstraint(
            model_name='financialvoucher',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('source_document_id', None), _negated=True), models.Q(('status', 'CANCELLED'), _negated=True)), fields=('company', 'source_document_type', 'source_document_id'), name='unique_source_document_voucher'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_transactions', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treasury_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_treasury_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_transactions', to='finance.financialvoucher'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['company', 'bank_account', 'transaction_date'], name='finance_tre_company_749370_idx'),
        ),
    ]
