# Generated by Django 6.0.3 on 2026-09-01 06:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('crm', '0005_alter_crmentity_code'),
        ('finance', '0012_pettycashcustodian_alter_expense_options_and_more'),
        ('hrm', '0015_alter_companypayrollpolicy_overtime_multiplier_and_more'),
        ('inventory', '0015_alter_itemserial_status_and_more'),
        ('operations', '0008_dutyassignment_temporary_service_and_more'),
        ('platform_core', '0004_usermoduleaccess'),
        ('purchasing', '0011_vendorreconciliation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasingAccountingIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('source_type', models.CharField(choices=[('VENDOR_BILL', 'Vendor Bill / Invoice'), ('VENDOR_PAYMENT', 'Vendor Payment'), ('PURCHASE_RETURN', 'Purchase Return'), ('VENDOR_CREDIT_NOTE', 'Vendor Credit Note')], max_length=30)),
                ('source_id', models.CharField(max_length=100)),
                ('source_number', models.CharField(max_length=100)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('currency_code', models.CharField(default='PKR', max_length=10)),
                ('status', models.CharField(choices=[('PENDING_CLASSIFICATION', 'Pending Classification'), ('READY', 'Ready for GL Posting'), ('BLOCKED', 'Blocked (Missing Mapping/Period/Tenant)'), ('POSTED_LATER', 'Posted Later'), ('REVERSED', 'Reversed / Voided')], default='PENDING_CLASSIFICATION', max_length=30)),
                ('blocking_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ap_control_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.chartofaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('crm_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchasing_accounting_integrations', to='crm.crmentity')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.currency')),
                ('finance_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.securityfinanceconfiguration')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchasing_po_integrations', to='purchasing.procurementdocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_purchasing_integrations', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_integrations', to='purchasing.vendor')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchasing_integrations', to='finance.financialvoucher')),
            ],
            options={
                'verbose_name_plural': 'Purchasing Accounting Integrations',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasingAccountingLinePreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('source_line_id', models.CharField(blank=True, max_length=100)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(default='INVENTORY_ITEM', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('is_tax_line', models.BooleanField(default=False)),
                ('is_unresolved', models.BooleanField(default=False)),
                ('unresolved_reason', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operations.servicecontract')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.costcenter')),
                ('credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.chartofaccount')),
                ('debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.chartofaccount')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hrm.department')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.purchasingaccountingintegration')),
                ('profit_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.profitcenter')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operations.operationalsite')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_core.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Purchasing Accounting Line Previews',
                'ordering': ['line_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasingItemAccountMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('account_classification', models.CharField(choices=[('INVENTORY_ASSET', 'Inventory Asset'), ('OPERATING_EXPENSE', 'Operating Expense'), ('FIXED_ASSET', 'Fixed Asset'), ('PREPAID_EXPENSE', 'Prepaid Expense'), ('OTHER', 'Other')], default='INVENTORY_ASSET', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchasing_item_debit_mappings', to='finance.chartofaccount')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasing_mappings', to='finance.expensecategory')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_mappings', to='inventory.item')),
                ('item_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasing_accounting_mappings', to='inventory.category')),
            ],
            options={
                'verbose_name_plural': 'Purchasing Item Account Mappings',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='purchasingaccountingintegration',
            index=models.Index(fields=['company', 'source_type', 'status'], name='finance_pur_company_663ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasingaccountingintegration',
            index=models.Index(fields=['company', 'transaction_date'], name='finance_pur_company_6a6753_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasingaccountingintegration',
            constraint=models.UniqueConstraint(fields=('company', 'source_type', 'source_id'), name='unique_company_purchasing_integration'),
        ),
    ]
