# Generated by Django 6.0.3 on 2026-09-01 08:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('crm', '0005_alter_crmentity_code'),
        ('finance', '0015_taxpaymentvoucher_taxperiod_taxtransaction_and_more'),
        ('hrm', '0015_alter_companypayrollpolicy_overtime_multiplier_and_more'),
        ('operations', '0008_dutyassignment_temporary_service_and_more'),
        ('purchasing', '0011_vendorreconciliation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='source_document_id',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='source_document_type',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='source_module',
        ),
        migrations.AddField(
            model_name='journal',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='journal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='finance_journalentries_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posting_event',
            field=models.CharField(blank=True, db_index=True, default='ORIGINAL', max_length=50),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='finance_journalentries_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(blank=True, choices=[('CLIENT_INVOICE', 'Client Invoice'), ('CLIENT_RECEIPT', 'Client Receipt / Collection'), ('VENDOR_BILL', 'Vendor Bill / Invoice'), ('VENDOR_PAYMENT', 'Vendor Payment'), ('PURCHASE_RETURN', 'Purchase Return'), ('VENDOR_CREDIT_NOTE', 'Vendor Credit Note'), ('EXPENSE', 'Direct Expense / Claim'), ('PAYROLL_ACCRUAL', 'Payroll Accrual'), ('SALARY_PAYMENT', 'Salary Payment Batch'), ('TAX_PAYMENT', 'Tax Payment / Challan'), ('TAX_ADJUSTMENT', 'Tax Adjustment'), ('CONTRA_TRANSFER', 'Treasury Contra Transfer'), ('MANUAL_JOURNAL', 'Manual Journal'), ('OPENING_BALANCE', 'Opening Balance')], db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='base_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='journal_lines', to='operations.servicecontract'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='journal_lines', to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='journal_lines', to='operations.operationalsite'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='source_line_reference',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='journal_lines', to='purchasing.vendor'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_type',
            field=models.CharField(choices=[('GENERAL', 'General Journal'), ('SALES', 'Sales Journal'), ('RECEIPTS', 'Receipts Journal'), ('PURCHASE', 'Purchase Journal'), ('PAYMENTS', 'Payments Journal'), ('PAYROLL', 'Payroll Journal'), ('TAX', 'Tax Journal'), ('EXPENSE', 'Expense Journal'), ('CASH', 'Cash Journal'), ('BANK', 'Bank Journal'), ('CONTRA', 'Contra Journal'), ('ADJUSTMENT', 'Adjustment Journal'), ('OPENING_BALANCE', 'Opening Balance Journal')], default='GENERAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entries', to='finance.journal'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='journal_lines', to='finance.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='journal_lines', to='finance.costcenter'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='crm_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='journal_lines', to='crm.crmentity'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='profit_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='journal_lines', to='finance.profitcenter'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'entry_date'], name='finance_uni_company_cc259e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'status'], name='finance_uni_company_3ff1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'source_type', 'source_id'], name='finance_uni_company_cdfd78_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['company', 'account'], name='finance_jou_company_e60f47_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['company', 'cost_center'], name='finance_jou_company_81d28c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['company', 'profit_center'], name='finance_jou_company_378377_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['company', 'crm_entity'], name='finance_jou_company_fc450f_idx'),
        ),
    ]
