# Generated by Django 6.0.3 on 2026-09-01 19:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('finance', '0016_remove_journalentry_source_document_id_and_more'),
        ('operations', '0008_dutyassignment_temporary_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='cash_flow_category',
            field=models.CharField(blank=True, choices=[('OPERATING', 'Operating Activities'), ('INVESTING', 'Investing Activities'), ('FINANCING', 'Financing Activities'), ('NON_CASH', 'Non-Cash Item')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='AllocationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('method', models.CharField(choices=[('BY_REVENUE', 'By Revenue'), ('BY_HEADCOUNT', 'By Headcount'), ('BY_SITE', 'By Site'), ('BY_FIXED_PERCENTAGE', 'By Fixed Percentage'), ('MANUAL', 'Manual')], default='BY_REVENUE', max_length=30)),
                ('target_type', models.CharField(choices=[('CONTRACT', 'Contract'), ('SITE', 'Site'), ('PROFIT_CENTER', 'Profit Center')], default='SITE', max_length=30)),
                ('percentage_or_weight', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('source_cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_sources', to='finance.costcenter')),
                ('target_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation_targets', to='operations.servicecontract')),
                ('target_profit_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation_targets', to='finance.profitcenter')),
                ('target_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation_targets', to='operations.operationalsite')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('view_financial_statements', 'Can view financial statements'), ('view_company_pl', 'Can view company P&L'), ('view_balance_sheet', 'Can view balance sheet'), ('view_cash_flow', 'Can view cash flow statement'), ('view_profitability', 'Can view profitability workspace'), ('view_client_profitability', 'Can view client profitability'), ('view_site_profitability', 'Can view site profitability'), ('manage_allocation_profiles', 'Can manage overhead allocation profiles'), ('export_financial_statements', 'Can export financial statements')],
                'abstract': False,
            },
        ),
    ]
