# Generated by Django 6.0.3 on 2026-09-01 20:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('finance', '0017_chartofaccount_cash_flow_category_allocationprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingperiod',
            options={'ordering': ['start_date'], 'permissions': [('view_period_close', 'Can view period close status and checklist'), ('run_close_checks', 'Can run period close readiness checks'), ('soft_close_period', 'Can soft close accounting period'), ('post_closing_adjustment', 'Can post adjustment entries during soft close'), ('final_close_period', 'Can perform final close on accounting period'), ('lock_period', 'Can lock closed accounting period'), ('reopen_period', 'Can reopen closed or soft-closed accounting period'), ('view_bank_reconciliation', 'Can view bank statement reconciliations'), ('import_bank_statement', 'Can import bank statements'), ('auto_match_bank', 'Can auto match bank statement transactions'), ('manual_match_bank', 'Can manually match bank statement transactions'), ('create_bank_adjustment', 'Can create bank charge adjustments'), ('close_bank_reconciliation', 'Can close bank statement reconciliation'), ('view_subledger_reconciliation', 'Can view subledger reconciliations'), ('resolve_reconciliation_exception', 'Can resolve reconciliation exceptions'), ('perform_cash_count', 'Can perform physical cash counts')]},
        ),
        migrations.AlterModelOptions(
            name='bankstatement',
            options={'ordering': ['-end_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='bankstatementline',
            options={'ordering': ['statement_date', 'id']},
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='checklist_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='close_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='soft_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='soft_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soft_closed_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_bank_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='file_import_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_bank_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='statement_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('RECONCILED', 'Reconciled'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='adjustment_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_adjustments', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='bank_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='external_transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='ignore_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='match_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='match_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='match_status',
            field=models.CharField(choices=[('AUTO_MATCHED', 'Auto Matched'), ('MANUALLY_MATCHED', 'Manually Matched'), ('PARTIAL_MATCH', 'Partial Match'), ('UNMATCHED', 'Unmatched'), ('IGNORED_WITH_REASON', 'Ignored with Reason')], default='UNMATCHED', max_length=30),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_bank_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='matched_cheque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_statement_lines', to='finance.cheque'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='matched_financial_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_statement_lines', to='finance.financialvoucher'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='matched_treasury_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_statement_lines', to='finance.treasurytransaction'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='running_balance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='statement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='finance.bankaccount'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='statement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='status',
            field=models.CharField(default='UNMATCHED', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('count_date', models.DateField()),
                ('system_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('physical_count', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('difference', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('variance_reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('VARIANCE_LOGGED', 'Variance Logged')], default='DRAFT', max_length=20)),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_counts', to='finance.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('counted_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='counted_cash_counts', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cash_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-count_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControlException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('exception_type', models.CharField(choices=[('UNBALANCED_CONTROL', 'Unbalanced Control Account Reconciliation'), ('UNRECONCILED_BANK', 'Unreconciled Bank Account'), ('CASH_VARIANCE', 'Physical Cash Count Variance'), ('UNPOSTED_SOURCE_EVENT', 'Unposted Source Financial Event'), ('UNCLEARED_OLD_CHEQUE', 'Uncleared Old Cheque'), ('SOFT_CLOSED_ADJUSTMENT_PENDING', 'Soft-Closed Adjustment Pending Approval'), ('PERIOD_CLOSE_BLOCKER', 'Period Close Blocker')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('BLOCKER', 'Blocker')], default='WARNING', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('EXPLICITLY_ACCEPTED', 'Explicitly Accepted')], default='OPEN', max_length=30)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_explanation', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_exceptions', to='finance.accountingperiod')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_control_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubledgerReconciliationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('ar_gl_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('ar_subledger_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('ar_difference', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('ap_gl_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('ap_subledger_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('ap_difference', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('payroll_gl_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('payroll_subledger_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('payroll_difference', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('tax_gl_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('tax_subledger_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('tax_difference', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('treasury_gl_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('treasury_operational_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('treasury_difference', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('is_all_reconciled', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subledger_snapshots', to='finance.accountingperiod')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'abstract': False,
            },
        ),
    ]
