# Generated by Django 6.0.3 on 2026-10-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_accountingperiod_options_and_more'),
        ('operations', '0019_deployment_location_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='operations.servicecontract'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='operations.operationalsite'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.servicecontract'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.operationalsite'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='operations.servicecontract'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='operations.operationalsite'),
        ),
    ]
