# Generated by Django 6.0.3 on 2026-08-01 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_purchaseorderitem_item'),
        ('services', '0007_servicemedia_is_deleted_serviceorder_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepartused',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_parts', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, help_text='The technician responsible for this repair (hardware or software)', limit_choices_to={'role__in': ['hardware_technician', 'software_technician']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_technical_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
