# Generated by Django 6.0.3 on 2026-08-04 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('services', '0008_servicepartused_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='crm_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crm.crmentity'),
        ),
        migrations.AddField(
            model_name='servicepartused',
            name='crm_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crm.crmentity'),
        ),
        migrations.AlterField(
            model_name='servicepartused',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
