# Generated by Django 6.0.3 on 2026-08-20 00:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_data_migrate_technicians'),
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, help_text="Optional system code (e.g., 'CEO')", max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('permissions', models.JSONField(blank=True, default=list, help_text="List of permission codes like 'security.site.manage'")),
                ('is_system', models.BooleanField(default=False, help_text='System roles cannot be deleted by tenants.')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Order or weight of the role.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='companies.company')),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company_role',
            field=models.ForeignKey(blank=True, help_text='Configurable granular permissions role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.companyrole'),
        ),
    ]
