# Generated by Django 6.0.3 on 2026-08-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_security_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_mode',
            field=models.CharField(choices=[('FULL_COMPANY', 'Full Company Access'), ('CUSTOM', 'Custom Access')], default='FULL_COMPANY', max_length=20),
        ),
    ]
