# Generated by Django 6.0.3 on 2026-08-09 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_designation_employee_employment_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerecord',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_record', to='hrm.employee'),
        ),
    ]
