# Generated by Django 6.0.3 on 2026-08-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_employeesalaryassignment_payrollperiod_payrollrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslipline',
            name='component_type',
            field=models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('TAX', 'Tax')], max_length=20),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='component_type',
            field=models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('TAX', 'Tax')], default='EARNING', max_length=20),
        ),
    ]
