# Generated by Django 6.0.3 on 2026-08-09 02:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial_platform_core'),
        ('finance', '0007_salesaccountingconfiguration'),
        ('hrm', '0008_payslip_tax_amount_alter_payslipline_component_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='payroll_runs', to='finance.journalentry'),
        ),
        migrations.CreateModel(
            name='PayrollAccountingConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('salary_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount')),
                ('salary_payable_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount')),
                ('tax_payable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company',), name='unique_active_payroll_accounting_config')],
            },
        ),
    ]
