# Generated by Django 6.0.3 on 2026-08-11 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_salesaccountingconfiguration'),
        ('hrm', '0009_payrollrun_journal_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollaccountingconfiguration',
            name='deduction_clearing_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount'),
        ),
    ]
