# Generated by Django 6.0.3 on 2026-08-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0010_phase8d_payroll_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystructurecomponent',
            name='formula',
            field=models.TextField(blank=True, default=''),
        ),
    ]
