# Generated by Django 6.0.3 on 2026-08-20 03:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('finance', '0009_bankaccount_bankstatement_bankstatementline_and_more'),
        ('hrm', '0012_candidate_candidatedocument_candidateverification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollDisbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('disbursement_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payroll_disbursements', to='finance.chartofaccount')),
                ('payment_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='payroll_disbursements', to='finance.financialvoucher')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='disbursements', to='hrm.payrollrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatutoryScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('scheme_type', models.CharField(choices=[('EOBI', 'EOBI'), ('SOCIAL_SECURITY', 'Social Security (SESSI/PESSI)'), ('INCOME_TAX', 'Income Tax')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount')),
                ('liability_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatutoryRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('employee_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage or flat amount depending on basis', max_digits=5)),
                ('employer_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage or flat amount depending on basis', max_digits=5)),
                ('wage_ceiling', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum wage basis for calculation', max_digits=12, null=True)),
                ('wage_floor', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum wage basis for calculation', max_digits=12, null=True)),
                ('is_flat_amount', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='hrm.statutoryscheme')),
            ],
            options={
                'ordering': ['-effective_from'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayslipStatutoryDeduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('employee_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('basis_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_deductions', to='hrm.payslip')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hrm.statutoryscheme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayslipDisbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hrm.payrolldisbursement')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='disbursement_records', to='hrm.payslip')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['COMPLETED', 'PROCESSING'])), fields=('company', 'payslip'), name='unique_active_payslip_disbursement')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatutoryEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('identifier', models.CharField(blank=True, help_text='e.g. EOBI Number or SSN', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_enrollments', to='hrm.employee')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='enrolled_employees', to='hrm.statutoryscheme')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'employee', 'scheme'), name='unique_active_employee_scheme')],
            },
        ),
    ]
