# Generated by Django 6.0.3 on 2026-08-25 01:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('finance', '0009_bankaccount_bankstatement_bankstatementline_and_more'),
        ('hrm', '0013_payrolldisbursement_statutoryscheme_statutoryrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPayrollPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('standard_monthly_hours', models.DecimalField(decimal_places=2, default=160.0, max_digits=5)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='payrollaccountingconfiguration',
            name='unique_active_payroll_accounting_config',
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='processed_payslip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_overtimes', to='hrm.payslip'),
        ),
        migrations.AlterField(
            model_name='overtimerecord',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSED', 'Processed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payrollaccountingconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('company',), name='unique_active_payroll_accounting_config'),
        ),
        migrations.AddField(
            model_name='companypayrollpolicy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company'),
        ),
        migrations.AddConstraint(
            model_name='companypayrollpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('company',), name='unique_active_company_payroll_policy'),
        ),
    ]
