# Generated by Django 6.0.3 on 2026-08-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0014_companypayrollpolicy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypayrollpolicy',
            name='overtime_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplier applied to the calculated hourly overtime rate.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='companypayrollpolicy',
            name='standard_monthly_hours',
            field=models.DecimalField(decimal_places=2, default=160.0, help_text='Used to derive hourly rate: Base Salary / Standard Monthly Hours.', max_digits=6),
        ),
    ]
