# Generated by Django 6.0.3 on 2026-09-04 05:18

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('finance', '0018_alter_accountingperiod_options_and_more'),
        ('hrm', '0015_alter_companypayrollpolicy_overtime_multiplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('document_type', models.CharField(choices=[('CNIC', 'CNIC'), ('POLICE_VERIFICATION', 'Police Verification'), ('OTHER_VERIFICATION', 'Other Verification'), ('CRO', 'Criminal Records Office (CRO)'), ('FINGERPRINT', 'Fingerprint Record'), ('EMPLOYMENT_CONTRACT', 'Employment Contract'), ('TERMS_AND_CONDITIONS', 'Terms & Conditions'), ('TRAINING_CERTIFICATE', 'Training Certificate'), ('EX_ARMY_DOCUMENT', 'Ex-Army Discharge/Document'), ('EDUCATION_DOCUMENT', 'Education Document'), ('OTHER', 'Other')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='hrm/employee_documents/')),
                ('document_number', models.CharField(blank=True, default='', max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeNextOfKin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('cnic_number', models.CharField(blank=True, default='', max_length=50)),
                ('relationship', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('training_type', models.CharField(max_length=100)),
                ('training_date', models.DateField()),
                ('institute_or_trainer', models.CharField(blank=True, default='', max_length=255)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='hrm/training_certificates/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='COMPLETED', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('event_type', models.CharField(max_length=50)),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatutorySchemeRateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('employee_default_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('employer_default_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-effective_from'],
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='employeestatutoryenrollment',
            name='unique_active_employee_scheme',
        ),
        migrations.AddField(
            model_name='employee',
            name='background_type',
            field=models.CharField(choices=[('CIVILIAN', 'Civilian'), ('EX_ARMY', 'Ex-Army'), ('OTHER', 'Other')], default='CIVILIAN', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='classification',
            field=models.CharField(choices=[('DIRECT', 'Direct - Field / Operational'), ('INDIRECT', 'Indirect - Office / Management')], default='DIRECT', help_text='DIRECT = Field guards/supervisors, INDIRECT = Office/Management staff', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='cnic_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated'), ('JUMP', 'Jump')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], default='SINGLE', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employeesalaryassignment',
            name='double_ot_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeesalaryassignment',
            name='single_ot_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeestatutoryenrollment',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeestatutoryenrollment',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeestatutoryenrollment',
            name='employee_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='employeestatutoryenrollment',
            name='employer_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='employeestatutoryenrollment',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeestatutoryenrollment',
            name='use_company_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='statutoryscheme',
            name='code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='statutoryscheme',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statutoryscheme',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statutoryscheme',
            name='employee_default_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Default Employee contribution %', max_digits=5),
        ),
        migrations.AddField(
            model_name='statutoryscheme',
            name='employer_default_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Default Employer contribution %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeesalaryassignment',
            name='salary_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hrm.salarystructure'),
        ),
        migrations.AlterField(
            model_name='statutoryscheme',
            name='liability_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='finance.chartofaccount'),
        ),
        migrations.AddConstraint(
            model_name='employeestatutoryenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('company', 'employee', 'scheme'), name='unique_active_employee_scheme'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeenextofkin',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company'),
        ),
        migrations.AddField(
            model_name='employeenextofkin',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='employeetraining',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company'),
        ),
        migrations.AddField(
            model_name='employeetraining',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='statutoryschemeratehistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company'),
        ),
        migrations.AddField(
            model_name='statutoryschemeratehistory',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='hrm.statutoryscheme'),
        ),
    ]
