# Generated by Django 6.0.3 on 2026-09-04 16:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('hrm', '0016_employeedocument_employeenextofkin_employeetraining_and_more'),
        ('operations', '0010_dutyroster_dutyreplacement_dutyswap_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workforceattendance',
            name='duty_roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_attendances', to='operations.dutyroster'),
        ),
        migrations.AddField(
            model_name='workforceattendance',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceattendance',
            name='is_finalized',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workforceattendance',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_attendances', to='operations.securitypost'),
        ),
        migrations.AddField(
            model_name='workforceattendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_workforce_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workforceattendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_attendances', to='hrm.shift'),
        ),
        migrations.AddField(
            model_name='workforceattendance',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_attendances', to='operations.operationalsite'),
        ),
        migrations.AlterField(
            model_name='workforceattendance',
            name='source',
            field=models.CharField(blank=True, default='CENTRAL_OFFICE', max_length=50),
        ),
        migrations.AlterField(
            model_name='workforceattendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('PAID_LEAVE', 'Paid Leave'), ('UNPAID_LEAVE', 'Unpaid Leave'), ('HOLIDAY', 'Holiday'), ('WEEKLY_OFF', 'Weekly Off'), ('HALF_DAY', 'Half Day'), ('LATE', 'Late'), ('ON_LEAVE', 'On Leave'), ('OFF_DAY', 'Off Day')], default='PRESENT', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeAttendanceState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('current_state', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_state', to='hrm.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_attendance_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JumpRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('absent_since', models.DateField()),
                ('jump_triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consecutive_absent_days', models.PositiveIntegerField(default=7)),
                ('reason', models.TextField(blank=True, default='7 consecutive unexcused absent days')),
                ('status', models.CharField(choices=[('ACTIVE_JUMP', 'Active JUMP'), ('RESTORED', 'Restored'), ('ACKNOWLEDGED', 'Acknowledged')], default='ACTIVE_JUMP', max_length=20)),
                ('reinstated_at', models.DateTimeField(blank=True, null=True)),
                ('reinstatement_notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jump_records', to='hrm.employee')),
                ('reinstated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinstated_jumps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-jump_triggered_at'],
            },
        ),
    ]
