# Generated by Django 6.0.3 on 2026-09-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0017_workforceattendance_duty_roster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypayrollpolicy',
            name='daily_rate_divisor',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Divisor used to derive daily duty rate from monthly base salary (e.g. 30.00, 26.00).', max_digits=5),
        ),
        migrations.AddField(
            model_name='companypayrollpolicy',
            name='holiday_pay_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Payable percentage for company holidays (default: 100.00%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='companypayrollpolicy',
            name='weekly_off_pay_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Payable percentage for scheduled weekly offs (default: 100.00%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='employeesalaryassignment',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Explicit daily payable duty rate if applicable. Overrides monthly base salary calculation.', max_digits=10, null=True),
        ),
    ]
