# Generated by Django 6.0.3 on 2026-09-05 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0018_companypayrollpolicy_daily_rate_divisor_and_more'),
        ('operations', '0011_securitypost_daily_pay_rate_dailydutypay'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerecord',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='ot_type',
            field=models.CharField(choices=[('SINGLE_OT', 'Single Overtime'), ('DOUBLE_OT', 'Double Overtime')], default='SINGLE_OT', max_length=20),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_records', to='operations.securitypost'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_records', to='operations.operationalsite'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='source',
            field=models.CharField(default='MANUAL', max_length=50),
        ),
    ]
