# Generated by Django 6.0.3 on 2026-09-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0019_overtimerecord_hourly_rate_overtimerecord_ot_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypayrollpolicy',
            name='default_double_ot_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional company-wide fallback double OT hourly rate.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='companypayrollpolicy',
            name='default_single_ot_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional company-wide fallback single OT hourly rate.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='companypayrollpolicy',
            name='enable_policy_ot_fallback',
            field=models.BooleanField(default=False, help_text='If True, allows deriving OT rate from base_salary / standard_monthly_hours * multiplier when no explicit rate is set.'),
        ),
    ]
