# Generated by Django 6.0.3 on 2026-09-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0021_payrollrun_advances_settled_payrollrun_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerecord',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
