# Generated by Django on 2026-09-23

from django.db import migrations
from django.db.models import Subquery, OuterRef


def sync_joining_dates(apps, schema_editor):
    EmploymentHistory = apps.get_model('hrm', 'EmploymentHistory')
    Employee = apps.get_model('hrm', 'Employee')

    # Subquery update: set effective_date = employee.hire_date for all JOINING/JOIN events
    subquery = Employee.objects.filter(id=OuterRef('employee_id')).values('hire_date')[:1]
    EmploymentHistory.objects.filter(
        event_type__in=['JOINING', 'JOIN'],
        employee__hire_date__isnull=False
    ).update(effective_date=Subquery(subquery))


def reverse_sync(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0027_alter_department_name_alter_designation_name'),
    ]

    operations = [
        migrations.RunPython(sync_joining_dates, reverse_sync),
    ]
