# Generated by Django 6.0.3 on 2026-09-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0028_sync_employment_history_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='background_type',
            field=models.CharField(choices=[('CIVILIAN', 'Civilian'), ('EX_ARMY', 'Ex-Army / Military'), ('EX_RANGERS', 'Rangers'), ('EX_MUJAHID', 'Mujahid Force'), ('EX_POLICE', 'Ex-Police / Law Enforcement'), ('OTHER', 'Other Background')], default='CIVILIAN', max_length=30),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('CNIC', 'CNIC'), ('POLICE_VERIFICATION', 'Police Verification'), ('OTHER_VERIFICATION', 'Other Verification'), ('CRO', 'Criminal Records Office (CRO)'), ('NADRA_VERIFICATION', 'NADRA Verification'), ('FINGERPRINT', 'Fingerprint Record'), ('EMPLOYMENT_CONTRACT', 'Employment Contract'), ('TERMS_AND_CONDITIONS', 'Terms & Conditions'), ('TRAINING_CERTIFICATE', 'Training Certificate'), ('EX_ARMY_DOCUMENT', 'Ex-Army Discharge/Document'), ('EX_RANGERS_DOCUMENT', 'Ex-Rangers Discharge/Document'), ('EX_MUJAHID_DOCUMENT', 'Ex-Mujahid Force Discharge/Document'), ('EDUCATION_DOCUMENT', 'Education Document'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
