# Generated by Django 6.0.3 on 2026-10-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0029_alter_employee_background_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='background_type',
            field=models.CharField(choices=[('CIVILIAN', 'Civil'), ('EX_ARMY', 'Ex-Army')], default='CIVILIAN', max_length=30),
        ),
    ]
