# Generated by Django 6.0.3 on 2026-10-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0030_alter_employee_background_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, choices=[('KHI', 'Karachi (KHI)'), ('LHR', 'Lahore (LHR)'), ('ISB', 'Islamabad (ISB)'), ('RAW', 'Rawalpindi (RAW)'), ('MUL', 'Multan (MUL)'), ('FSD', 'Faisalabad (FSD)'), ('PEW', 'Peshawar (PEW)'), ('QTA', 'Quetta (QTA)')], db_index=True, default='KHI', help_text='Station / City code for workforce deployment scoping (e.g. KHI, LHR)', max_length=20),
        ),
    ]
