# Generated by Django 6.0.3 on 2026-07-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0001_initial_platform_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Primary warehouse for the company'),
        ),
    ]
