# Generated by Django 6.0.3 on 2026-08-05 23:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial_platform_core'),
        ('platform_core', '0002_warehouse_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('document_type', models.CharField(help_text='e.g. JOURNAL, PO, INVOICE', max_length=50)),
                ('prefix', models.CharField(help_text='e.g. GEN-20260806', max_length=50)),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('company', 'document_type', 'prefix'), name='unique_company_doc_seq')],
            },
        ),
    ]
