# Generated by Django 6.0.3 on 2026-07-30 21:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial_platform_core'),
        ('inventory', '0005_remove_vendor_balance_category_is_deleted_and_more'),
        ('platform_core', '0002_warehouse_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('SPARE_PART', 'Spare Part'), ('CONSUMABLE', 'Consumable'), ('ASSET', 'Asset'), ('EQUIPMENT', 'Equipment'), ('RENTAL', 'Rental'), ('DIGITAL', 'Digital'), ('BUNDLE', 'Bundle')], default='PRODUCT', max_length=20)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('unit_of_measure', models.CharField(default='pcs', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sellable', models.BooleanField(default=True)),
                ('is_purchasable', models.BooleanField(default=True)),
                ('track_inventory', models.BooleanField(default=True)),
                ('track_serial_number', models.BooleanField(default=False)),
                ('track_batch', models.BooleanField(default=False)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minimum_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='platform_core.warehouse')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='inventory.item')),
            ],
            options={
                'ordering': ['item', 'warehouse'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemSerial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('serial_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('SOLD', 'Sold'), ('IN_TRANSIT', 'In Transit'), ('RETURNED', 'Returned'), ('DEFECTIVE', 'Defective')], default='IN_STOCK', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_serials', to='platform_core.warehouse')),
            ],
            options={
                'ordering': ['item', 'serial_number'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['barcode'], name='inventory_i_barcode_209767_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='inventory_i_name_637656_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['sku'], name='inventory_i_sku_3e99d5_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['company'], name='inventory_i_company_4b99ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('sku', ''), _negated=True), ('sku__isnull', False)), fields=('company', 'sku'), name='unique_company_sku'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('item_code', ''), _negated=True), ('item_code__isnull', False)), fields=('company', 'item_code'), name='unique_company_item_code'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('barcode', ''), _negated=True), ('barcode__isnull', False)), fields=('company', 'barcode'), name='unique_company_barcode'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['warehouse'], name='inventory_i_warehou_3d818e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['item'], name='inventory_i_item_id_392f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['company'], name='inventory_i_company_0da7f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(fields=('item', 'warehouse'), name='unique_item_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='itemserial',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('serial_number', ''), _negated=True), ('serial_number__isnull', False)), fields=('company', 'serial_number'), name='unique_company_serial'),
        ),
    ]
