# Generated by Django 6.0.3 on 2026-08-05 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_purchaseorder_procurement_document_and_more'),
        ('purchasing', '0002_alter_approvalhistory_action_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorledger',
            name='procurement_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='purchasing.procurementdocument'),
        ),
    ]
