# Generated by Django 6.0.3 on 2026-08-18 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('inventory', '0011_vendorledger_procurement_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Text Area'), ('NUMBER', 'Number'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('DATETIME', 'Date/Time'), ('SELECT', 'Dropdown/Select'), ('MULTI_SELECT', 'Multi-Select')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('options', models.JSONField(blank=True, help_text='List of choices for SELECT/MULTI_SELECT', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='inventory.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('value', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='inventory.itemfielddefinition')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='inventory.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='itemfielddefinition',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='unique_company_field_key'),
        ),
        migrations.AddConstraint(
            model_name='itemfieldvalue',
            constraint=models.UniqueConstraint(fields=('item', 'field_definition'), name='unique_item_field_value'),
        ),
    ]
