# Generated by Django 6.0.3 on 2026-08-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_itemfielddefinition_itemfieldvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfielddefinition',
            name='default_value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
