# Generated by Django 6.0.3 on 2026-08-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_make_vendor_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemserial',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('SOLD', 'Sold'), ('IN_TRANSIT', 'In Transit'), ('RETURNED', 'Returned'), ('DEFECTIVE', 'Defective'), ('ISSUED', 'Issued')], default='IN_STOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment'), ('OPENING_BALANCE', 'Opening Balance'), ('PURCHASE', 'Purchase'), ('PURCHASE_RETURN', 'Purchase Return'), ('SALE', 'Sale'), ('SALE_RETURN', 'Sale Return'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('SERVICE_USAGE', 'Service Usage'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('DAMAGE', 'Damage'), ('LOSS', 'Loss'), ('EMPLOYEE_ISSUE', 'Employee Issue'), ('EMPLOYEE_RETURN', 'Employee Return')], max_length=20),
        ),
    ]
