# Generated by Django 6.0.3 on 2026-09-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_itemserial_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment'), ('OPENING_BALANCE', 'Opening Balance'), ('PURCHASE', 'Purchase'), ('PURCHASE_RETURN', 'Purchase Return'), ('SALE', 'Sale'), ('SALE_RETURN', 'Sale Return'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('SERVICE_USAGE', 'Service Usage'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('DAMAGE', 'Damage'), ('LOSS', 'Loss'), ('EMPLOYEE_ISSUE', 'Employee Issue'), ('EMPLOYEE_RETURN', 'Employee Return'), ('SITE_ISSUE', 'Site Issue'), ('SITE_RETURN', 'Site Return')], max_length=20),
        ),
    ]
