# Generated by Django 6.0.3 on 2026-08-13 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('crm', '0001_initial'),
        ('finance', '0008_budget_budgetline_and_more'),
        ('hrm', '0011_phase8d_formula_engine'),
        ('reports', '0002_reportsubscription_generatedreport_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('target_type', models.CharField(choices=[('REVENUE', 'Revenue'), ('SALES', 'Sales'), ('GROSS_PROFIT', 'Gross Profit'), ('NEW_CUSTOMERS', 'New Customers'), ('COLLECTIONS', 'Collections')], max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.costcenter')),
                ('crm_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crm.crmentity')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hrm.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hrm.employee')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['company', 'target_type', 'period_start', 'period_end'], name='reports_tar_company_fc381e_idx')],
            },
        ),
    ]
