# Generated by Django 6.0.3 on 2026-07-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('mobile', 'Mobile Repair Shop'), ('security', 'Security Services'), ('retail', 'Retail'), ('wholesale', 'Wholesale'), ('restaurant', 'Restaurant / Food'), ('hotel', 'Hotel / Hospitality'), ('hospital', 'Hospital'), ('clinic', 'Clinic'), ('pharmacy', 'Pharmacy'), ('school', 'School / Education'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('logistics', 'Logistics / Transport'), ('real_estate', 'Real Estate'), ('automotive', 'Automotive'), ('beauty', 'Beauty / Salon'), ('gym', 'Gym / Fitness'), ('agriculture', 'Agriculture'), ('ngo', 'NGO / Non-Profit'), ('professional_services', 'Professional Services'), ('other', 'Other')], db_index=True, default='other', help_text='The primary business vertical for this company.', max_length=30),
        ),
    ]
