# Generated by Django 6.0.3 on 2026-08-04 00:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial_platform_core'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('entity_type', models.CharField(choices=[('PERSON', 'Person'), ('COMPANY', 'Company'), ('GOVERNMENT', 'Government'), ('NGO', 'NGO'), ('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('LEAD', 'Lead'), ('PARTNER', 'Partner'), ('EMPLOYEE', 'Employee'), ('CONTRACTOR', 'Contractor'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('preferred_currency', models.CharField(default='PKR', max_length=10)),
                ('preferred_language', models.CharField(default='en', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entities', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_entities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CRM Entities',
            },
        ),
        migrations.CreateModel(
            name='CRMCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('type', models.CharField(choices=[('phone', 'Phone'), ('meeting', 'Meeting'), ('email', 'Email'), ('note', 'Note'), ('whatsapp', 'WhatsApp'), ('visit', 'Visit'), ('support', 'Support'), ('quotation', 'Quotation')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='crm.crmentity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CRMAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('file', models.FileField(upload_to='crm/attachments/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.crmentity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CRMNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('text', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='crm.crmentity')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CRMTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='crmentity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entities', to='crm.crmtag'),
        ),
        migrations.CreateModel(
            name='CRMContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('receives_invoices', models.BooleanField(default=False)),
                ('receives_quotes', models.BooleanField(default=False)),
                ('receives_notifications', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.crmentity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('entity',), name='unique_primary_contact_per_entity')],
            },
        ),
        migrations.CreateModel(
            name='CRMAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('address_type', models.CharField(choices=[('Billing', 'Billing'), ('Shipping', 'Shipping'), ('Office', 'Office'), ('Warehouse', 'Warehouse'), ('Home', 'Home'), ('Other', 'Other')], default='Other', max_length=20)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='crm.crmentity')),
            ],
            options={
                'verbose_name_plural': 'CRM Addresses',
                'constraints': [models.UniqueConstraint(condition=models.Q(('address_type', 'Billing'), ('is_default', True)), fields=('entity', 'address_type'), name='unique_default_billing_address'), models.UniqueConstraint(condition=models.Q(('address_type', 'Shipping'), ('is_default', True)), fields=('entity', 'address_type'), name='unique_default_shipping_address')],
            },
        ),
        migrations.CreateModel(
            name='CRMRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('relationship_type', models.CharField(choices=[('Company -> Employee', 'Company -> Employee'), ('Supplier -> Sales Rep', 'Supplier -> Sales Rep'), ('Parent Company -> Subsidiary', 'Parent Company -> Subsidiary'), ('Vendor -> Manufacturer', 'Vendor -> Manufacturer'), ('Partner -> Distributor', 'Partner -> Distributor'), ('Other', 'Other')], default='Other', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='crm.crmentity')),
                ('to_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='crm.crmentity')),
            ],
            options={
                'unique_together': {('from_entity', 'to_entity', 'relationship_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='crmentity',
            unique_together={('company', 'code')},
        ),
    ]
