# Generated by Django 6.0.3 on 2026-08-18 20:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMEntityRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('role', models.CharField(choices=[('PERSON', 'Person'), ('COMPANY', 'Company'), ('GOVERNMENT', 'Government'), ('NGO', 'NGO'), ('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('LEAD', 'Lead'), ('PARTNER', 'Partner'), ('EMPLOYEE', 'Employee'), ('CONTRACTOR', 'Contractor'), ('OTHER', 'Other')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='crm.crmentity')),
            ],
            options={
                'verbose_name_plural': 'CRM Entity Roles',
                'constraints': [models.UniqueConstraint(fields=('entity', 'role'), name='unique_entity_role')],
            },
        ),
    ]
