# Generated by Django 6.0.3 on 2026-08-18 20:48

from django.db import migrations


def populate_roles(apps, schema_editor):
    CRMEntity = apps.get_model('crm', 'CRMEntity')
    CRMEntityRole = apps.get_model('crm', 'CRMEntityRole')

    roles_to_create = []
    for entity in CRMEntity.objects.exclude(entity_type=''):
        roles_to_create.append(
            CRMEntityRole(
                entity=entity,
                role=entity.entity_type,
                company_id=entity.company_id
            )
        )
    
    if roles_to_create:
        CRMEntityRole.objects.bulk_create(roles_to_create, ignore_conflicts=True)

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_add_crm_entity_role'),
    ]

    operations = [
        migrations.RunPython(populate_roles, migrations.RunPython.noop),
    ]
