# Generated by Django 6.0.3 on 2026-08-20 17:24

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('crm', '0003_populate_crm_roles'),
        ('hrm', '0013_payrolldisbursement_statutoryscheme_statutoryrule_and_more'),
        ('operations', '0006_usersiteaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('opportunity_number', models.CharField(max_length=100)),
                ('stage', models.CharField(choices=[('LEAD', 'Lead'), ('QUALIFIED', 'Qualified'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('AWARDED', 'Awarded'), ('WON', 'Won'), ('LOST', 'Lost')], default='LEAD', max_length=50)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('probability', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('loss_reason', models.CharField(blank=True, max_length=255)),
                ('competitor', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('converted_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_opportunities', to='operations.servicecontract')),
                ('crm_entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='opportunities', to='crm.crmentity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'unique_together': {('company', 'opportunity_number')},
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('proposal_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('INTERNAL_REVIEW', 'Internal Review'), ('SUBMITTED', 'Submitted'), ('REVISED', 'Revised'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('scope', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='crm.opportunity')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'proposal_number', 'version')},
            },
        ),
        migrations.CreateModel(
            name='OpportunityAward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('method', models.CharField(choices=[('EMAIL', 'Email'), ('LETTER', 'Letter'), ('PORTAL', 'Portal'), ('OTHER', 'Other')], default='LETTER', max_length=20)),
                ('award_reference', models.CharField(blank=True, max_length=100)),
                ('award_date', models.DateField(default=datetime.date.today)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='crm/bd/awards/%Y/%m/%d/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='crm.opportunity')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='awards', to='crm.proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProposalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.designation')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crm.proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
