# Generated by Django 6.0.3 on 2026-08-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_opportunity_proposal_opportunityaward_proposalline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmentity',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
