# Generated by Django 6.0.3 on 2026-08-05 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial_platform_core'),
        ('crm', '0001_initial'),
        ('inventory', '0009_purchaseorder_crm_entity_vendor_crm_entity_and_more'),
        ('platform_core', '0002_warehouse_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('module', models.CharField(default='purchasing', max_length=50)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'name', 'module')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('step_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('approver_role', models.CharField(blank=True, max_length=50)),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='purchasing.approvalworkflow')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('workflow', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('document_id', models.PositiveIntegerField()),
                ('document_model', models.CharField(default='purchasing.ProcurementDocument', max_length=100)),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DELEGATED', 'Delegated')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.approvalstep')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='history', to='purchasing.approvalworkflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcurementDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('document_type', models.CharField(choices=[('RFQ', 'Request for Quotation'), ('QUOTATION', 'Quotation'), ('PURCHASE_ORDER', 'Purchase Order'), ('PURCHASE_REQUEST', 'Purchase Request'), ('GOODS_RECEIPT', 'Goods Receipt'), ('PURCHASE_RETURN', 'Purchase Return'), ('VENDOR_INVOICE', 'Vendor Invoice'), ('DEBIT_NOTE', 'Debit Note'), ('BLANKET_ORDER', 'Blanket Order'), ('CONTRACT_PURCHASE', 'Contract Purchase')], default='PURCHASE_ORDER', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('SENT', 'Sent'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30)),
                ('number', models.CharField(max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('document_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=12)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_procurement_documents', to=settings.AUTH_USER_MODEL)),
                ('crm_entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='procurement_documents', to='crm.crmentity')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_procurement_documents', to=settings.AUTH_USER_MODEL)),
                ('parent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_documents', to='purchasing.procurementdocument')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_documents', to='platform_core.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Procurement Documents',
            },
        ),
        migrations.CreateModel(
            name='ProcurementAuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('event', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='purchasing.procurementdocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcurementAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('file', models.FileField(upload_to='purchasing/attachments/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchasing.procurementdocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcurementNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('note_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External'), ('VENDOR', 'Vendor Note'), ('APPROVAL', 'Approval Note')], default='INTERNAL', max_length=20)),
                ('text', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_rel', to='purchasing.procurementdocument')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcurementTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='purchasing.procurementtag'),
        ),
        migrations.CreateModel(
            name='ProcurementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('received_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('billed_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('returned_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.procurementdocument')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='procurement_lines', to='inventory.item')),
            ],
            options={
                'ordering': ['line_number'],
                'unique_together': {('document', 'line_number')},
            },
        ),
        migrations.AddIndex(
            model_name='procurementdocument',
            index=models.Index(fields=['company', 'document_type', 'status'], name='purchasing__company_a134ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='procurementdocument',
            unique_together={('company', 'number')},
        ),
    ]
