# Generated by Django 6.0.3 on 2026-08-21 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_alter_approvalhistory_action_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhistory',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='purchasing.approvalworkflow'),
        ),
    ]
