# Generated by Django 6.0.3 on 2026-08-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_alter_approvalhistory_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalhistory',
            name='document_id',
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='document_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
