# Generated by Django 6.0.3 on 2026-08-30 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('crm', '0005_alter_crmentity_code'),
        ('inventory', '0015_alter_itemserial_status_and_more'),
        ('purchasing', '0004_alter_approvalhistory_document_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Vendor Categories',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('tax_number', models.CharField(blank=True, help_text='NTN / GST / VAT Number', max_length=100)),
                ('registration_number', models.CharField(blank=True, help_text='Company registration / SECP', max_length=100)),
                ('payment_terms', models.CharField(blank=True, default='Net 30', max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_title', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('iban', models.CharField(blank=True, max_length=100)),
                ('swift_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked'), ('PENDING_REVIEW', 'Pending Review')], default='ACTIVE', max_length=30)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Vendor rating out of 5')),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('crm_entity', models.OneToOneField(blank=True, help_text='Linked CRM entity for shared contacts, communications, and universal ledger', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_profile', to='crm.crmentity')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='purchasing.vendorcategory')),
            ],
            options={
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('document_type', models.CharField(choices=[('AGREEMENT', 'Agreement'), ('TAX_CERTIFICATE', 'Tax Certificate'), ('BANK_DETAILS', 'Bank Details'), ('QUOTATION', 'Quotation'), ('PRICE_LIST', 'Price List'), ('WARRANTY', 'Warranty'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='purchasing/vendor_documents/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='purchasing.vendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor Documents',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('vendor_sku', models.CharField(blank=True, help_text='Vendor-specific part/catalog number', max_length=100)),
                ('vendor_price', models.DecimalField(decimal_places=2, default=0, help_text='Quoted supplier unit price', max_digits=15)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('minimum_order_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(default=0, help_text='Expected delivery lead time in days')),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_preferred', models.BooleanField(default=False, help_text='Mark as preferred supplier for this item')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_supplies', to='inventory.item')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_items', to='purchasing.vendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor Items',
                'ordering': ['-is_preferred', 'item__name'],
                'abstract': False,
                'unique_together': {('vendor', 'item')},
            },
        ),
    ]
