# Generated by Django 6.0.3 on 2026-08-30 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_vendorcategory_vendor_vendordocument_vendoritem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementdocument',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_procurement_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='procurement_documents', to='purchasing.vendor'),
        ),
        migrations.AddField(
            model_name='procurementline',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementline',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='procurementline',
            name='vendor_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_lines', to='purchasing.vendoritem'),
        ),
        migrations.AddField(
            model_name='procurementline',
            name='vendor_sku',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
