# Generated by Django 6.0.3 on 2026-08-30 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_procurementdocument_approval_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalhistory',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='procurementline',
            name='accepted_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='procurementline',
            name='parent_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_lines', to='purchasing.procurementline'),
        ),
        migrations.AddField(
            model_name='procurementline',
            name='rejected_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='procurementline',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='procurementaudittrail',
            name='event',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('STATUS_CHANGE', 'Status Change'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='procurementdocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('SENT', 'Sent'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received'), ('POSTED', 'Posted'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30),
        ),
    ]
