# Generated by Django 6.0.3 on 2026-08-30 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0007_alter_approvalhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementdocument',
            name='ap_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='freight_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='match_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='match_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_procurement_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='payment_status',
            field=models.CharField(default='UNPAID', max_length=30),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='vendor_invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='procurementdocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('SENT', 'Sent'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received'), ('PENDING_MATCH', 'Pending Match'), ('MATCHED', 'Matched'), ('MISMATCH', 'Mismatch'), ('POSTED', 'Posted'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30),
        ),
    ]
