# Generated by Django 6.0.3 on 2026-08-31 03:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('crm', '0005_alter_crmentity_code'),
        ('inventory', '0015_alter_itemserial_status_and_more'),
        ('platform_core', '0004_usermoduleaccess'),
        ('purchasing', '0009_vendorpayment_vendorpaymentallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('return_number', models.CharField(max_length=100)),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged Goods'), ('DEFECTIVE', 'Defective Equipment'), ('WRONG_ITEM', 'Wrong Item Received'), ('EXCESS_QUANTITY', 'Excess Quantity Received'), ('QUALITY_REJECTED', 'Quality Inspection Rejected'), ('WARRANTY_RETURN', 'Warranty / RMA Return'), ('OTHER', 'Other / Commercial Reason')], default='DEFECTIVE', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('total_return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('crm_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_returns', to='crm.crmentity')),
                ('goods_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_purchase_returns', to='purchasing.procurementdocument')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_purchase_returns', to='purchasing.procurementdocument')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_returns', to='purchasing.vendor')),
                ('vendor_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_purchase_returns', to='purchasing.procurementdocument')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_returns', to='platform_core.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Purchase Returns',
                'ordering': ['-return_date', '-created_at'],
                'abstract': False,
                'unique_together': {('company', 'return_number')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('description', models.TextField(blank=True)),
                ('received_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('previously_returned_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('return_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reason', models.CharField(blank=True, max_length=50)),
                ('serial_numbers', models.JSONField(blank=True, default=list)),
                ('is_rejected_at_grn', models.BooleanField(default=False)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('grn_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_return_lines', to='purchasing.procurementline')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_return_lines', to='inventory.item')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchasereturn')),
            ],
            options={
                'verbose_name_plural': 'Purchase Return Lines',
                'ordering': ['line_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorCreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('credit_note_number', models.CharField(max_length=100)),
                ('credit_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(default='POSTED', max_length=30)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_notes', to=settings.AUTH_USER_MODEL)),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='purchasing.purchasereturn')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='credit_notes', to='purchasing.vendor')),
                ('vendor_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='purchasing.procurementdocument')),
            ],
            options={
                'verbose_name_plural': 'Vendor Credit Notes',
                'ordering': ['-credit_date', '-created_at'],
                'abstract': False,
                'unique_together': {('company', 'credit_note_number')},
            },
        ),
    ]
