# Generated by Django 6.0.3 on 2026-08-31 19:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('purchasing', '0010_purchasereturn_purchasereturnline_vendorcreditnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('reconciliation_number', models.CharField(max_length=100)),
                ('statement_date', models.DateField(default=django.utils.timezone.now)),
                ('as_of_date', models.DateField(default=django.utils.timezone.now, help_text='Transaction cutoff date for system balance')),
                ('vendor_reported_balance', models.DecimalField(decimal_places=2, default=0, help_text="Balance reported on vendor's statement", max_digits=15)),
                ('system_balance', models.DecimalField(decimal_places=2, default=0, help_text='Calculated outstanding payable in Zorvex', max_digits=15)),
                ('variance', models.DecimalField(decimal_places=2, default=0, help_text='system_balance - vendor_reported_balance', max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('MATCHED', 'Matched (Zero Variance)'), ('VARIANCE', 'Variance Detected'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=30)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Investigation notes regarding discrepancies')),
                ('resolution_notes', models.TextField(blank=True, help_text='Action notes explaining how variance was reconciled')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_vendor_statements', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_vendor_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='purchasing.vendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor Reconciliations',
                'ordering': ['-statement_date', '-created_at'],
                'abstract': False,
                'unique_together': {('company', 'reconciliation_number')},
            },
        ),
    ]
