# Generated by Django 6.0.3 on 2026-08-10 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial_platform_core'),
        ('crm', '0001_initial'),
        ('hrm', '0009_payrollrun_journal_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('crm_entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operational_sites', to='crm.crmentity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('contract_code', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('crm_entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='service_contracts', to='crm.crmentity')),
                ('sites', models.ManyToManyField(blank=True, related_name='service_contracts', to='operations.operationalsite')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('billing_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pay_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effective_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contract_rates', to='hrm.designation')),
                ('service_contract', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rates', to='operations.servicecontract')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='servicecontract',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'contract_code'), name='unique_active_contract_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='contractrate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'service_contract', 'designation', 'effective_date'), name='unique_active_contract_rate'),
        ),
    ]
