# Generated by Django 6.0.3 on 2026-08-19 22:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('hrm', '0012_candidate_candidatedocument_candidateverification_and_more'),
        ('operations', '0004_dailyactivityreport_dailyactivityentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStaffingRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('required_headcount', models.PositiveIntegerField(default=0)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='staffing_requirements', to='hrm.designation')),
                ('service_contract', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='staffing_requirements', to='operations.servicecontract')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='staffing_requirements', to='hrm.shift')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='staffing_requirements', to='operations.operationalsite')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
