# Generated by Django 6.0.3 on 2026-08-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_qachecklisttemplate_qachecklistitem_qafinding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyassignment',
            name='temporary_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='duty_assignments', to='operations.temporaryservicerequest'),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='duty_assignments', to='operations.deployment'),
        ),
    ]
