# Generated by Django 6.0.3 on 2026-09-04 06:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('crm', '0005_alter_crmentity_code'),
        ('hrm', '0016_employeedocument_employeenextofkin_employeetraining_and_more'),
        ('operations', '0008_dutyassignment_temporary_service_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deployments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deployment',
            name='assignment_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary')], default='PERMANENT', max_length=20),
        ),
        migrations.AddField(
            model_name='deployment',
            name='crm_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='deployments', to='crm.crmentity'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='relief_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deployment',
            name='relieved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relieved_deployments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deployment',
            name='relieved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('RELIEVED', 'Relieved'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='SecurityPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('post_name', models.CharField(max_length=255)),
                ('post_code', models.CharField(blank=True, default='', max_length=50)),
                ('required_headcount', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('required_designation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='security_posts', to='hrm.designation')),
                ('service_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_posts', to='operations.servicecontract')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_posts', to='operations.operationalsite')),
            ],
            options={
                'ordering': ['site', 'post_name'],
            },
        ),
        migrations.AddField(
            model_name='deployment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='operations.securitypost'),
        ),
        migrations.AddConstraint(
            model_name='securitypost',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'site', 'post_name'), name='unique_active_post_name_per_site'),
        ),
    ]
