# Generated by Django 6.0.3 on 2026-09-04 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('hrm', '0016_employeedocument_employeenextofkin_employeetraining_and_more'),
        ('operations', '0009_deployment_assigned_by_deployment_assignment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('duty_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('REPLACED', 'Replaced'), ('SWAPPED', 'Swapped'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('is_replacement', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_rosters', to='operations.deployment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='duty_rosters', to='hrm.employee')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_rosters', to='operations.securitypost')),
                ('replacement_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_duties', to='operations.dutyroster')),
                ('rostered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rostered_duties', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='duty_rosters', to='hrm.shift')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='duty_rosters', to='operations.operationalsite')),
            ],
            options={
                'ordering': ['-duty_date', 'site', 'post'],
            },
        ),
        migrations.CreateModel(
            name='DutyReplacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('duty_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(default='ASSIGNED', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_duty_replacements', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('original_employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='replaced_duties', to='hrm.employee')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_replacements', to='operations.securitypost')),
                ('replacement_employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='replacement_coverages', to='hrm.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='duty_replacements', to='hrm.shift')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='duty_replacements', to='operations.operationalsite')),
                ('original_roster', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='replacement_records', to='operations.dutyroster')),
                ('replacement_roster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_source', to='operations.dutyroster')),
            ],
            options={
                'ordering': ['-duty_date', 'site'],
            },
        ),
        migrations.CreateModel(
            name='DutySwap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('employee_a', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='roster_swaps_as_a', to='hrm.employee')),
                ('employee_b', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='roster_swaps_as_b', to='hrm.employee')),
                ('roster_a', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='swaps_as_a', to='operations.dutyroster')),
                ('roster_b', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='swaps_as_b', to='operations.dutyroster')),
                ('swapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_roster_swaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostShiftRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('required_headcount', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requirements', to='operations.securitypost')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='post_requirements', to='hrm.shift')),
            ],
            options={
                'ordering': ['post', 'shift'],
            },
        ),
        migrations.AddConstraint(
            model_name='dutyroster',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'SCHEDULED')), fields=('company', 'employee', 'duty_date', 'shift'), name='unique_active_scheduled_duty_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='postshiftrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'post', 'shift'), name='unique_active_post_shift_req'),
        ),
    ]
