# Generated by Django 6.0.3 on 2026-09-05 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('crm', '0005_alter_crmentity_code'),
        ('finance', '0018_alter_accountingperiod_options_and_more'),
        ('hrm', '0018_companypayrollpolicy_daily_rate_divisor_and_more'),
        ('operations', '0010_dutyroster_dutyreplacement_dutyswap_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securitypost',
            name='daily_pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Post-specific daily payable duty rate (e.g. 500.00). Overrides employee home rate during coverage.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='DailyDutyPay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('duty_date', models.DateField(db_index=True)),
                ('attendance_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('PAID_LEAVE', 'Paid Leave'), ('UNPAID_LEAVE', 'Unpaid Leave'), ('HOLIDAY', 'Holiday'), ('WEEKLY_OFF', 'Weekly Off'), ('HALF_DAY', 'Half Day'), ('LATE', 'Late'), ('ON_LEAVE', 'On Leave'), ('OFF_DAY', 'Off Day')], default='PRESENT', max_length=30)),
                ('is_replacement_duty', models.BooleanField(default=False)),
                ('rate_source', models.CharField(choices=[('POST_RATE', 'Post Daily Rate'), ('CONTRACT_RATE', 'Contract Designation Rate'), ('REPLACED_EMPLOYEE_RATE', 'Replaced Guard Rate'), ('EMPLOYEE_DAILY_RATE', 'Employee Explicit Daily Rate'), ('EMPLOYEE_MONTHLY_DIVISOR', 'Employee Monthly Salary / Divisor'), ('MANUAL_OVERRIDE', 'Manual Rate Override')], default='EMPLOYEE_MONTHLY_DIVISOR', max_length=50)),
                ('rate_source_reference', models.CharField(blank=True, default='', max_length=200)),
                ('daily_payable_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payable_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculation_status', models.CharField(choices=[('CALCULATED', 'Calculated'), ('RECALCULATED', 'Recalculated'), ('UNRESOLVED', 'Unresolved Rate'), ('FINALIZED', 'Finalized in Payroll')], default='CALCULATED', max_length=30)),
                ('is_frozen', models.BooleanField(default=False, help_text='Locked once consumed by finalized payroll. Cannot be modified.')),
                ('unresolved_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_duty_pays', to='hrm.workforceattendance')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_duty_pays', to='crm.crmentity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_duty_pays', to='operations.servicecontract')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.costcenter')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.currency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_duty_pays', to='hrm.employee')),
                ('home_deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_daily_duty_pays', to='operations.deployment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_duty_pays', to='operations.securitypost')),
                ('replaced_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_daily_duty_pays', to='hrm.employee')),
                ('replacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_duty_pays', to='operations.dutyreplacement')),
                ('roster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_duty_pays', to='operations.dutyroster')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_duty_pays', to='operations.operationalsite')),
            ],
            options={
                'ordering': ['-duty_date', 'employee'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('roster__isnull', False)), fields=('company', 'employee', 'duty_date', 'roster'), name='unique_active_daily_duty_pay_with_roster'), models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('roster__isnull', True)), fields=('company', 'employee', 'duty_date'), name='unique_active_daily_duty_pay_without_roster')],
            },
        ),
    ]
