# Generated by Django 6.0.3 on 2026-09-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_employeepayrollcalculation_payrolladdition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayrollcalculation',
            name='pessi_employee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeepayrollcalculation',
            name='pessi_employer_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeepayrollcalculation',
            name='sessi_employee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeepayrollcalculation',
            name='sessi_employer_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollcalculationline',
            name='rate_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
