# Generated by Django 6.0.3 on 2026-09-05 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0021_payrollrun_advances_settled_payrollrun_approved_at_and_more'),
        ('operations', '0013_employeepayrollcalculation_pessi_employee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayrollcalculation',
            name='payroll_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_calculations', to='hrm.payrollrun'),
        ),
        migrations.AddField(
            model_name='employeepayrollcalculation',
            name='payslip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_calculation_records', to='hrm.payslip'),
        ),
        migrations.AddField(
            model_name='payrolladdition',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrolldeduction',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
