# Generated by Django 6.0.3 on 2026-09-07 08:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('crm', '0005_alter_crmentity_code'),
        ('hrm', '0023_employee_confirmation_date_and_more'),
        ('inventory', '0016_alter_stockmovement_movement_type'),
        ('operations', '0014_employeepayrollcalculation_payroll_run_and_more'),
        ('platform_core', '0004_usermoduleaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentissue',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_issues', to='crm.crmentity'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_issues', to='operations.servicecontract'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='custody_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee Custody'), ('SITE', 'Site Custody')], default='EMPLOYEE', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='damage_severity',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='purpose',
            field=models.CharField(blank=True, default='', help_text='Reason/purpose for issuance', max_length=150),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='resolution_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='resolution_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_equipment_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentissue',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='equipment_issues', to='hrm.employee'),
        ),
        migrations.AlterField(
            model_name='equipmentissue',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged'), ('WRITTEN_OFF', 'Written Off')], default='ISSUED', max_length=20),
        ),
        migrations.CreateModel(
            name='EquipmentIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('incident_type', models.CharField(choices=[('LOST', 'Lost Equipment'), ('DAMAGED', 'Damaged Equipment'), ('UNUSABLE', 'Unusable / Defective')], default='DAMAGED', max_length=20)),
                ('incident_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('condition_description', models.TextField(blank=True, default='')),
                ('evidence_notes', models.TextField(blank=True, default='')),
                ('estimated_loss_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('APPROVED_WRITE_OFF', 'Approved Write-Off'), ('RECOVERED', 'Recovered'), ('REPAIRED', 'Repaired & Restored')], default='REPORTED', max_length=30)),
                ('approved_resolution', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('payroll_deduction_recommended', models.BooleanField(default=False)),
                ('payroll_deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_incidents', to='hrm.employee')),
                ('equipment_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='operations.equipmentissue')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipment_incidents', to='inventory.item')),
                ('item_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_incidents', to='inventory.itemserial')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_equipment_incidents', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_equipment_incidents', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_incidents', to='operations.operationalsite')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_incidents', to='platform_core.warehouse')),
            ],
            options={
                'ordering': ['-incident_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityItemProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('security_category', models.CharField(choices=[('UNIFORM', 'Uniform'), ('SHOES_PPE', 'Shoes / PPE'), ('RADIO_COMMS', 'Radio / Communication Equipment'), ('TORCH_SECURITY', 'Torch / Security Equipment'), ('CCTV_ELECTRONIC', 'CCTV / Electronic Equipment'), ('ACCESS_CONTROL', 'Access-Control Equipment'), ('CONSUMABLES', 'Consumables'), ('CONTROLLED_EQUIPMENT', 'Controlled / Regulated Equipment'), ('WEAPONS_AMMO', 'Weapons / Ammunition'), ('OTHER', 'Other Security Equipment')], default='OTHER', max_length=50)),
                ('is_controlled', models.BooleanField(default=False, help_text='Controlled or regulated security equipment')),
                ('requires_authorization', models.BooleanField(default=False, help_text='Requires manager/armorer authorization to issue/return')),
                ('license_required', models.BooleanField(default=False)),
                ('license_reference', models.CharField(blank=True, default='', max_length=100)),
                ('permit_reference', models.CharField(blank=True, default='', max_length=100)),
                ('permit_expiry_date', models.DateField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, default='', help_text='Designated armory rack, locker, or storage zone', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to='inventory.item')),
            ],
            options={
                'ordering': ['item__name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityStoreProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('store_type', models.CharField(choices=[('MAIN_STORE', 'Main Store'), ('BRANCH_STORE', 'Branch Store'), ('SITE_STORE', 'Operational Site Store'), ('ARMORY', 'Armory / Controlled Store')], default='MAIN_STORE', max_length=30)),
                ('is_armory', models.BooleanField(default=False)),
                ('requires_strong_auth', models.BooleanField(default=False, help_text='Strong authorization required for issues from this store')),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('site', models.ForeignKey(blank=True, help_text='Operational site if this store is situated at a client facility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_stores', to='operations.operationalsite')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_stores', to='hrm.employee')),
                ('warehouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to='platform_core.warehouse')),
            ],
            options={
                'ordering': ['warehouse__name'],
                'abstract': False,
            },
        ),
    ]
