# Generated by Django 6.0.3 on 2026-09-07 10:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_logo_company_phone_and_more'),
        ('operations', '0016_incidentreport_assigned_to_incidentreport_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(default='Standard Inspection Policy', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('base_score', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('warning_threshold', models.DecimalField(decimal_places=2, default=Decimal('85.00'), max_digits=5)),
                ('escalation_threshold', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5)),
                ('critical_threshold', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5)),
                ('critical_priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', max_length=20)),
                ('escalation_priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('warning_priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
            ],
            options={
                'verbose_name': 'Inspection Policy',
                'verbose_name_plural': 'Inspection Policies',
                'ordering': ['-effective_from', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='supervisorinspection',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='operations.inspectionpolicy'),
        ),
        migrations.CreateModel(
            name='InspectionCriterionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('criterion_code', models.CharField(choices=[('GUARD_PRESENCE', 'Guard Presence Verified'), ('UNIFORM_CONDITION', 'Uniform Condition'), ('EQUIPMENT_CONDITION', 'Equipment Condition'), ('POST_CLEANLINESS', 'Post Cleanliness Condition'), ('DOCUMENTATION_ORDER', 'Documentation In Order'), ('TURNOUT_BEARING', 'Turnout and Bearing')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('deduction_weight', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='companies.company')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='operations.inspectionpolicy')),
            ],
            options={
                'verbose_name': 'Inspection Criterion Policy',
                'verbose_name_plural': 'Inspection Criterion Policies',
                'abstract': False,
                'unique_together': {('policy', 'criterion_code')},
            },
        ),
    ]
