# Generated by Django 6.0.3 on 2026-09-07 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0023_employee_confirmation_date_and_more'),
        ('inventory', '0016_alter_stockmovement_movement_type'),
        ('operations', '0017_inspectionpolicy_supervisorinspection_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='equipment_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_incident_reports', to='operations.equipmentincident'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='item_serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='inventory.itemserial'),
        ),
        migrations.AddField(
            model_name='supervisorinspection',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_supervisor_inspections', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='supervisorinspection',
            name='inspected_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_supervisor_inspections', to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='supervisorinspection',
            name='item_serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_supervisor_inspections', to='inventory.itemserial'),
        ),
    ]
