# Generated by Django 6.0.3 on 2026-09-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_incidentreport_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='location_monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Location-specific monthly salary for this deployment (e.g. 25000.00, 35000.00). Overrides default employee salary.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='securitypost',
            name='monthly_pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Post-specific monthly base salary (e.g. 28000.00). Used to derive daily duty pay rate (monthly / 30).', max_digits=12, null=True),
        ),
    ]
