# Generated by Django 6.0.3 on 2026-10-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_crmentity_code'),
        ('operations', '0019_deployment_location_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrate',
            name='service_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='operations.servicecontract'),
        ),
        migrations.AlterField(
            model_name='dailyactivityreport',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to='operations.operationalsite'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='crm_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='crm.crmentity'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='service_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='operations.servicecontract'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='operations.operationalsite'),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_assignments', to='operations.operationalsite'),
        ),
        migrations.AlterField(
            model_name='dutyreplacement',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_replacements', to='operations.operationalsite'),
        ),
        migrations.AlterField(
            model_name='dutyroster',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_rosters', to='operations.operationalsite'),
        ),
        migrations.AlterField(
            model_name='extraduty',
            name='service_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_duties', to='operations.servicecontract'),
        ),
        migrations.AlterField(
            model_name='extraduty',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_duties', to='operations.operationalsite'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='operations.operationalsite'),
        ),
        migrations.AlterField(
            model_name='operationalsite',
            name='crm_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_sites', to='crm.crmentity'),
        ),
        migrations.AlterField(
            model_name='qainspection',
            name='operational_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.operationalsite'),
        ),
        migrations.AlterField(
            model_name='qainspection',
            name='service_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.servicecontract'),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='crm_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_contracts', to='crm.crmentity'),
        ),
        migrations.AlterField(
            model_name='sitestaffingrequirement',
            name='service_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_requirements', to='operations.servicecontract'),
        ),
        migrations.AlterField(
            model_name='sitestaffingrequirement',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_requirements', to='operations.operationalsite'),
        ),
    ]
