# reports/services/analytics/registry.py

KPI_REGISTRY = {
    "revenue": {
        "code": "revenue",
        "name": "Revenue",
        "description": "Total revenue generated from operations",
        "category": "finance",
        "unit": "currency",
        "source_service": "FinancialStatementsReportingService",
        "calculation_method": "get_profit_and_loss",
        "data_key": "revenue",
        "required_permission": "finance",
        "supported_periods": ["daily", "weekly", "monthly", "yearly"],
        "supported_chart_types": ["line", "bar", "card"],
    },
    "expenses": {
        "code": "expenses",
        "name": "Expenses",
        "description": "Total operating expenses",
        "category": "finance",
        "unit": "currency",
        "source_service": "FinancialStatementsReportingService",
        "calculation_method": "get_profit_and_loss",
        "data_key": "expenses",
        "required_permission": "finance",
        "supported_periods": ["daily", "weekly", "monthly", "yearly"],
        "supported_chart_types": ["line", "bar", "card"],
    },
    "net_profit": {
        "code": "net_profit",
        "name": "Net Profit",
        "description": "Total revenue minus expenses",
        "category": "finance",
        "unit": "currency",
        "source_service": "FinancialStatementsReportingService",
        "calculation_method": "get_profit_and_loss",
        "data_key": "net_profit",
        "required_permission": "finance",
        "supported_periods": ["daily", "weekly", "monthly", "yearly"],
        "supported_chart_types": ["line", "bar", "card"],
    },
    "gross_margin": {
        "code": "gross_margin",
        "name": "Gross Margin",
        "description": "(Revenue - COGS) / Revenue",
        "category": "finance",
        "unit": "percent",
        "source_service": "FinancialRatioService",
        "calculation_method": "get_gross_margin",
        "required_permission": "finance",
        "supported_periods": ["daily", "weekly", "monthly", "yearly"],
        "supported_chart_types": ["line", "card"],
    },
    "current_ratio": {
        "code": "current_ratio",
        "name": "Current Ratio",
        "description": "Current Assets / Current Liabilities",
        "category": "finance",
        "unit": "ratio",
        "source_service": "FinancialRatioService",
        "calculation_method": "get_current_ratio",
        "required_permission": "finance",
        "supported_periods": ["monthly", "yearly"],
        "supported_chart_types": ["line", "card"],
    },
    "asset_turnover": {
        "code": "asset_turnover",
        "name": "Asset Turnover",
        "description": "Revenue / Total Assets",
        "category": "finance",
        "unit": "ratio",
        "source_service": "FinancialRatioService",
        "calculation_method": "get_asset_turnover",
        "required_permission": "finance",
        "supported_periods": ["monthly", "yearly"],
        "supported_chart_types": ["line", "card"],
    },
    "ar_balance": {
        "code": "ar_balance",
        "name": "Accounts Receivable Balance",
        "description": "Total outstanding accounts receivable",
        "category": "finance",
        "unit": "currency",
        "source_service": "CustomerBalanceService",
        "calculation_method": "get_total_balance",
        "required_permission": "finance",
        "supported_periods": ["daily", "weekly", "monthly"],
        "supported_chart_types": ["line", "bar", "card"],
    },
    "cash_balance": {
        "code": "cash_balance",
        "name": "Cash Balance",
        "description": "Total cash and cash equivalents",
        "category": "finance",
        "unit": "currency",
        "source_service": "CashMovementReportingService",
        "calculation_method": "get_total_cash",
        "required_permission": "finance",
        "supported_periods": ["daily", "weekly", "monthly"],
        "supported_chart_types": ["line", "bar", "card"],
    },
    "inventory_value": {
        "code": "inventory_value",
        "name": "Inventory Value",
        "description": "Total value of inventory on hand",
        "category": "inventory",
        "unit": "currency",
        "source_service": "SupplyChainReportingService",
        "calculation_method": "get_total_inventory_value",
        "required_permission": "inventory",
        "supported_periods": ["daily", "weekly", "monthly"],
        "supported_chart_types": ["line", "bar", "card"],
    },
    "active_orders": {
        "code": "active_orders",
        "name": "Active Orders",
        "description": "Total active operations/orders",
        "category": "operations",
        "unit": "count",
        "source_service": "OperationsMetricsReportingService",
        "calculation_method": "get_active_deployments",
        "required_permission": "operations",
        "supported_periods": ["daily", "weekly", "monthly"],
        "supported_chart_types": ["line", "card"],
    }
}
