# Generated by Django 6.0.3 on 2026-04-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('sales', '0004_possession_sale_pos_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='possession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['created_at']},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='sale',
                    name='profit',
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "sales_sale" ADD COLUMN IF NOT EXISTS "profit" numeric(12, 2) DEFAULT 0 NOT NULL;',
                    reverse_sql='ALTER TABLE "sales_sale" DROP COLUMN IF EXISTS "profit";',
                )
            ]
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='sales_custo_phone_43e3c6_idx'),
        ),
    ]
