# Generated by Django 6.0.3 on 2026-08-01 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_purchaseorderitem_item'),
        ('sales', '0006_customer_is_deleted_customer_total_credit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customercreditledger',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sale_items', to='inventory.item'),
        ),
    ]
