# Generated by Django 6.0.3 on 2026-08-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_salesaccountingconfiguration'),
        ('sales', '0008_customer_crm_entity_customercreditledger_crm_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercreditledger',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='sale',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.journalentry'),
        ),
    ]
