# Generated by Django 6.0.3 on 2026-08-18 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_make_product_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercreditledger',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='sales.customer'),
        ),
    ]
